### PR TITLE
QML performance tests

### PR DESCRIPTION
**Pull request by sonicflare**
Here is small qml performance tests. To have some understanding of performance implications of some functionality. 

The normal benchmark tests were not an option, as all qml code must run in gui thread, which benchmark tests does not atm allow you to do. 

Example of running test:
```
                                  main.QmlEngineCreationTest      100	   3449703 ns/op            3 ms/op
                        main.QmlEngineCreationAndDestroyTest      100	   4370805 ns/op            4 ms/op
                                     main.QmlEngineLoadForm1      100	      8540 ns/op
                                   main.QmlEngineCreateForm1      100	      1195 ns/op
                                     main.QmlEngineLoadForm2      100	     36401 ns/op
                                   main.QmlEngineCreateForm2      100	      1102 ns/op
                                     main.QmlEngineLoadForm3      100	    239740 ns/op
                                   main.QmlEngineCreateForm3      100	     17204 ns/op
                                     main.QmlEngineLoadForm4      100	    264181 ns/op
                                   main.QmlEngineCreateForm4      100	     19422 ns/op
                             main.QmlEngineCallingJsFunction      100	       847 ns/op
                    main.QmlEngineChangingObjectPropertyInJs      100	       773 ns/op
                    main.QmlEngineChangingObjectPropertyInGo      100	      1771 ns/op
                               main.QmlEnginePassingGoObject      100	      2042 ns/op
                  main.QmlEngineCallingGoModelFunctionFromJs      100	      1456 ns/op
     main.QmlEngineCallingGoModelFunctionFromJsWithArguments      100	      1370 ns/op

```

### CODE REVIEW

**Comment by pjoe** [comment]
Any particular reason for not using the standard golang benchmark stuff (http://golang.org/pkg/testing/)?

Also some of these are tests are somewhat artificial and won't show QML performance bottlenecks, e.g. having a single property in the root context is not an issue, but having 100 might :)

**Comment by sonicflare** [comment]
You have to start from something. 
The native benchmark does not allow to run tests from gui thread, and it is always run as go routine.
The go-qml have explicit checks for that, and result in panic.  

Fun fact, but the actually go-qml author created an issue about that, but just only for tests. 
https://github.com/golang/go/issues/7905

**Comment by pjoe** [comment]
Also these general go-qml maybe belongs better in the go-qml project?

**Comment by sonicflare** [comment]
It does not profile much of a go-ql code, rather than qml engine itself. 
The purpose of this, is to guide the design/refactor. To make intelligent decisions about where and how to write stuff that is interfaced with qml.
Like I don't know what thing is faster, but with this i can tell the relative performance implications of some structure in qml.

**Comment by pjoe** [comment]
Ok, I just meant that this didn't look very lime specific to me, but more like general go-qml benchmarks, so maybe doesn't belong too well in the lime repo as it is right now

**Comment by sonicflare** [comment]
That is valid point. It can go to some utility repo. 
it should be in tests, but go convention does not do that.

**Comment by pjoe** [comment]
Why not in go-qml? The stuff you have now seems to me to be very valuable for that project :)

**Comment by zidoms** [comment]
As @pjoe said these tests are related to go-qml we can't do anything about them in limetext code. We need benchmarks so we could enhance qml frontend code.

**Comment by quarnster** [comment]
These benchmarks would be more suitable in the [go-qml](https://github.com/go-qml/qml) repo

**Pull request closed without merging**
